Repository Interacao-Humano-Computador/2021.1-Prefeitura-de-Concordia, pull requests merged in 2021-09, with the labels that each got.

#40 #39 Elenco de personas
  docs/analiseRequisitos/personas.md
Labels: documentation, Análise de Requisitos

#38 #36 Documento das Metas de Usabilidade
  docs/analiseRequisitos/metasUsabilidade.md
  mkdocs.yml
Labels: documentation, Análise de Requisitos

#41 #37 Guia de estilo
  docs/analiseRequisitos/guiaDeEstilo.md
  docs/images/analiseRequisitos/guiaEstilo/formularioAutoatendimento.png
  docs/images/analiseRequisitos/guiaEstilo/formularioIluminacao.png
  docs/images/analiseRequisitos/guiaEstilo/formularioSelecao.png
  docs/images/analiseRequisitos/guiaEstilo/gridPaginaAtual.png
  docs/images/analiseRequisitos/guiaEstilo/iconesRotativos.png
  docs/images/analiseRequisitos/guiaEstilo/iconesRotativos/atendimentosConselhoTutelar.png
  docs/images/analiseRequisitos/guiaEstilo/iconesRotativos/defesaCivil.png
  docs/images/analiseRequisitos/guiaEstilo/iconesRotativos/gerencieImovel.png
  docs/images/analiseRequisitos/guiaEstilo/iconesRotativos/legislacaoMunicipal.png
  docs/images/analiseRequisitos/guiaEstilo/iconesRotativos/licitacao.png
  docs/images/analiseRequisitos/guiaEstilo/iconesRotativos/ouvidoria.png
  docs/images/analiseRequisitos/guiaEstilo/iconesRotativos/processoDigital.png
  docs/images/analiseRequisitos/guiaEstilo/iconesRotativos/recursosMultaCovid.png
  docs/images/analiseRequisitos/guiaEstilo/iconesRotativos/salaEmpreendedor.png
  docs/images/analiseRequisitos/guiaEstilo/iconesRotativos/solicitaIluminacao.png
  docs/images/analiseRequisitos/guiaEstilo/janelaGaleria.png
  docs/images/analiseRequisitos/guiaEstilo/janelaInformacao.png
  docs/images/analiseRequisitos/guiaEstilo/janelaNoticia.png
  docs/images/analiseRequisitos/guiaEstilo/openSansTipografia.png
  docs/images/analiseRequisitos/guiaEstilo/paletaLogo.png
  docs/images/analiseRequisitos/guiaEstilo/paletaSite.png
  docs/images/analiseRequisitos/guiaEstilo/redesSociais.png
  docs/images/analiseRequisitos/guiaEstilo/robotoCondensedTipografia.png
  docs/images/brasaoPrefeitura.png
  docs/images/brasaoPrefeituraFavicon.png
  mkdocs.yml
Labels: documentation, Análise de Requisitos

#42 Criacao do documento e descricao
  docs/analiseRequisitos/caracteristicasDaPlatafoma.md
  docs/images/analiseRequisitos/Ciclomayhew.png
  docs/images/analiseRequisitos/Tecnologias.png
  docs/images/analiseRequisitos/autoatendimento.png
  docs/images/analiseRequisitos/defesa.png
  docs/images/analiseRequisitos/home.png
  docs/images/analiseRequisitos/legislação.png
  docs/images/analiseRequisitos/transparencia.png
  mkdocs.yml
Labels: documentation, Análise de Requisitos

#48 #44 Documentação 3 ponto de controle
  docs/apresentacoes/p1.md
  docs/apresentacoes/p2.md
  docs/apresentacoes/p3.md
  mkdocs.yml
Labels: documentation, Análise de Requisitos

#49 #47 Planejamento análise de tarefas
  docs/analiseTarefas/planejamento.md
  mkdocs.yml
Labels: documentation, Design Avaliação e Desenvolvimento

#43 #35 Principio e diretrizes
  docs/analiseRequisitos/principios_e_diretrizes.md
  docs/images/principios_de_diretrizes/image-erro-2.png
  docs/images/principios_de_diretrizes/image-erro1.png
  docs/images/principios_de_diretrizes/image1.png
  docs/images/principios_de_diretrizes/image2.png
  docs/images/principios_de_diretrizes/image3.png
  mkdocs.yml
Labels: documentation, Análise de Requisitos

#59 #45 Storyboards da equipe
  docs/apresentacoes/p1.md
  docs/apresentacoes/p2.md
  docs/apresentacoes/p3.md
  docs/images/nivel1/storyboard-Gasto-no-portal-da-transparencia.png
  docs/images/nivel1/storyboardAcessoNoticias.png
  docs/images/nivel1/storyboardCertidaoNegativa.png
  docs/images/nivel1/storyboardHistoriaCidade.png
  docs/images/nivel1/storyboardSolicitacaoIluminacao.png
  docs/nivel1/storyboards.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: documentation, Design Avaliação e Desenvolvimento

#56 #55 Revisão dos documentos
  docs/analiseRequisitos/metasUsabilidade.md
  docs/analiseRequisitos/personas.md
  docs/analiseRequisitos/principios_e_diretrizes.md
Labels: documentation

#58 #57 Documentação 4 ponto de controle
  docs/apresentacoes/p4.md
  mkdocs.yml
Labels: documentation, Design Avaliação e Desenvolvimento

#64 #62 Documentação 5 ponto de controle
  docs/apresentacoes/p5.md
  mkdocs.yml
Labels: documentation, Design Avaliação e Desenvolvimento

#61 #54 Planejamento do Protótipo de Baixa Fidelidade
  docs/nivel2/planejamento.md
  mkdocs.yml
Labels: documentation, Design Avaliação e Desenvolvimento

#63 #53 Prototipação de baixa fidelidade
  docs/nivel2/prototipo.md
  mkdocs.yml
Labels: documentation, Design Avaliação e Desenvolvimento

#85 #78 Verificação dos storyboards
  docs/verificacao/storyboards.md
  mkdocs.yml
Labels: documentation, Verificação

#84 #75 Verificação características da plataforma
  docs/verificacao/caracteristicas_da_plataforma.md
  docs/verificacao/introducao.md
  docs/verificacao/template_verificacao.md
  mkdocs.yml
Labels: documentation, Verificação
